---
title: "ER model"
author: "Xiaochuan Yang"
date: "19/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Erdos-Renyi random graphs

Given $n$ nodes, connect any pair of nodes with probability $p$, independently with all other pairs. The induced random graph with vertex set $V$ and edge set $E$ is called Erdos-Renyi random graph, denoted by $G(n,p)$. 

```{r}
install.packages("igraph")
library(igraph)
```

We simulate these gaphs wit R package igraph. 

```{r}
g <- barabasi.game(500, power = 1.2, m = NULL, out.dist = NULL, out.seq = NULL,
  out.pref = FALSE, zero.appeal = 1, directed = FALSE,
  algorithm ="psumtree", start.graph = NULL)
plot(g, vertex.label= NA, edge.arrow.size=0.02,vertex.size = 0.5, xlab = "Scale-free network model")
```


## Cards

Let's generate a deck of cards. 

```{r}
cards <-c(2:10, "J","Q","K")
suits <- c("♠", "♥", "♦", "♣")
deck <- paste0(rep(cards,length(suits)),rep(suits,each=length(cards)))
sample(deck)
```

## Financial data

```{r}
prices <- rep(200,255)
for (i in 2:255){prices[i] <- prices[i-1]+(runif(1)-0.5)*5}
prices1 <- rep(200,255)
for (i in 2:255){prices1[i] <- prices1[i-1]+(runif(1)-0.5)*10}
plot(prices1, type="l")
lines(prices, col="blue")
```



